# Generated by Django 6.0.4 on 2026-04-13 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('category', models.CharField(choices=[('tourist', 'Turista'), ('premium', 'Premium')], max_length=10)),
                ('floor', models.IntegerField()),
                ('price_daily', models.DecimalField(decimal_places=2, max_digits=8)),
                ('capacity', models.IntegerField(default=2)),
                ('features', models.JSONField(default=list)),
                ('equipment', models.JSONField(default=list)),
                ('images', models.JSONField(default=list)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
